# -*- coding: utf-8 -*-
"""sea_level_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZOVTzxr3U_tIU3FR5-FhCJ3p1amhp5d
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

def draw_plot():
    # Import the data from "epa-sea-level.csv"
    df = pd.read_csv('epa-sea-level.csv')

    # Create a scatter plot using Matplotlib
    plt.figure(figsize=(10, 5))
    plt.scatter(df['Year'], df['CSIRO Adjusted Sea Level'], c='blue', label='Original Data')

    # Use the linregress function to get the slope and y-intercept of the line of best fit
    slope, intercept, r_value, p_value, std_err = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])

    # Predict sea level rise in 2050 using all data
    x_pred = list(range(1880, 2051))
    y_pred = [(slope * year + intercept) for year in x_pred]
    plt.plot(x_pred, y_pred, c='red', label='Line of Best Fit (1880-2050)')

    # Predict sea level rise in 2050 using data from year 2000 onwards
    df_recent = df[df['Year'] >= 2000]
    slope_recent, intercept_recent, r_value_recent, p_value_recent, std_err_recent = linregress(df_recent['Year'], df_recent['CSIRO Adjusted Sea Level'])
    x_pred_recent = list(range(2000, 2051))
    y_pred_recent = [(slope_recent * year + intercept_recent) for year in x_pred_recent]
    plt.plot(x_pred_recent, y_pred_recent, c='green', label='Line of Best Fit (2000-2050)')

    # Set labels and title
    plt.xlabel('Year')
    plt.ylabel('Sea Level (inches)')
    plt.title('Rise in Sea Level')

    # Add legend
    plt.legend()

    # Save and return the image
    plt.savefig('sea_level_plot.png')
    return plt.gca().figure